---
title: "tree models"
author: "EJ Arce"
date: "12/2/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Cross validations

```{r}
# run kfold cv
tuned <- tune.svm(STEM ~ .-IDnum-GSSyear-X1-DegreeField, data = train,
                  tunecontrol = tune.control(cross=5))
summary(tuned)
```

```{r}
p <- tune.svm(STEM ~ .-IDnum-GSSyear-X1-DegreeField, data = train,
                   gamma = (.000001:20), cost = (.00001:100))
plot(p)
```

```{r}
library(ggplot2)
plot1 <- ggplot(GSS8, aes(x = STEM)) +
  geom_bar(position = "fill", aes(col = sex))
plot1
```

```{r}
GSS8 <- subset(GSS4, select = -c(ageism, racism, prestige,IDnum,GSSyear,
                                 IndusCode))
GSS8 <- GSS8 %>%
  mutate(STEM =
           ifelse(
             DegreeField %in% c(
               "Agriculture",
               "Allied health",
               "Biology",
               "Chemistry",
               "Computer science",
               "Electronics",
               "Engineering",
               "Environment science/studies",
               "Food science/nutrition/culinary arts",
               "Forestry",
               "General sciences",
               "Geology",
               "Gerontology",
               "HealthIndustry & techn",
               "Information technology",
               "Mathmatics",
               "Medicine",
               "Pharmacy",
               "Physics",
               "Psychology"
             ), 1, 0
           )
  )
GSS8$STEM <- as.factor(GSS8$STEM)
GSS8$PlaceLived16 <- as.factor(GSS8$PlaceLived16)
GSS8$GovOrPriv <- as.factor(GSS8$GovOrPriv)
GSS8 <- subset(GSS8, select = -DegreeField)
GSS8 <- drop_na(GSS8)
train <- sample(1:nrow(GSS8), nrow(GSS8) * .75)
```

```{r}
library(tree)
library(gbm)
t1 <- tree(STEM~.,GSS8)
boost <- gbm(STEM~., data = GSS8[train,],
             shrinkage = .1, interaction.depth = 1, n.trees = 50)
```

```{r}
library(randomForest)

set.seed(35)
bag <- randomForest(STEM~., data = GSS8, type = classification,
                    subset = train, importance = TRUE)
summary(bag)
```

```{r}
# svm
svm1 <- svm(STEM ~ ., data = GSS8[train,])
summary(svm1)

tuned <- tune.svm(svm1, data = train,
                  tunecontrol = tune.control(cross=5))
summary(tuned)
```

