---
title: "the work"
author: "EJ Arce, Den Ivanov, Matthew Yancheff"
date: "11/29/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
# Import the data
GSS3 <- read.csv("https://raw.githubusercontent.com/ejarce/243project/master/college_major_set_1/GSS3.csv")
prestige <- read.csv("https://raw.githubusercontent.com/ejarce/243project/master/college_major_set_1/GSSprestige.csv") 
```

### Tidying the data

```{r}
library(dplyr)
prestige <- prestige[-c(4513,4514),]
prestige <- prestige %>%
  rename(IDnum = Idnum) %>%
  dplyr::select(1,2,4)
GSS3 <- GSS3[-4513,]
#GSS3 <- distinct(GSS3)
GSS3$IDnum <- as.numeric(GSS3$IDnum)
GSS3$GSSyear <- as.numeric(GSS3$GSSyear)
prestige$IDnum <- as.numeric(prestige$IDnum)
prestige$GSSyear <- as.numeric(prestige$GSSyear)
GSS3$pctColleagueWdegree <- as.numeric(GSS3$pctColleagueWdegree)
GSS3$hrsLastWk <- as.numeric(GSS3$hrsLastWk)
GSS3$Age <- as.numeric(GSS3$Age)
GSS3 <- left_join(GSS3, prestige, by = c("IDnum", "GSSyear"))
GSS3[GSS3 == "Not applicable"] <- NA
GSS3[GSS3 == "No answer"] <- NA
GSS3$colltype <- ifelse(GSS3$colltype %in% c(
  "Private for-profit, 2-year",
  "Private for-profit, less-than 2-year",
  "Private not-for-profit, 4-year or above",
  "Private for-profit, 4-year or above",
  "Private not-for-profit, 2-year or less"), "Private",
  ifelse(GSS3$colltype %in% c(
    "Public, 4-year or above",
    "Public, 2-year"), "Public", "none"))
GSS3 <- GSS3 %>%
  mutate(racism = ifelse(racism == "Yes", "Yes",
                         ifelse(racism == "No", "No", NA))) %>%
  mutate(BornHere = ifelse(BornHere == "Yes", 1,
                           ifelse(BornHere == "No", 0, NA))) %>%
  mutate(ageism = ifelse(ageism == c("Dont know", "No answer", "Not applicable"), NA,
                         ifelse(ageism == "No", "No", "Yes"))) %>%
  mutate(income = ifelse(income == "$10000 - 14999", 10000, 
         ifelse(income == "$1000 to 2999", 1000,
                ifelse(income == "$15000 - 19999", 15000,
                       ifelse(income == "$20000 - 24999", 20000,
                              ifelse(income == "$25000 or more", 25000,
                                     ifelse(income == "$3000 to 3999", 3000,
                                            ifelse(income == "$4000 to 4999", 4000,
          ifelse(income == "$5000 to 5999", 5000,
                 ifelse(income == "$6000 to 6999", 6000,
                        ifelse(income == "$7000 to 7999", 7000,
                               ifelse(income == "$8000 to 9999", 8000,
                                      ifelse(income == "Lt $1000", 0, NA))))))))))))) %>%
  mutate(selfEmploy = ifelse(selfEmploy == "Self-employed", 1, 0)) %>%
  mutate(GovOrPriv = ifelse(GovOrPriv == "Government", "Government",
                            ifelse(GovOrPriv == "Private", "Private", NA))) %>%
  mutate(PlaceLived16 = ifelse(PlaceLived16 == "Town lt 50000", 0,
                               ifelse(PlaceLived16 == "50000 to 250000", 50000,
                                      ifelse(PlaceLived16 == "City gt 250000", 250000,
                                             ifelse(PlaceLived16 == "Big-city suburb","Big-city suburb", NA)))))
GSS3$ageism <- as.factor(GSS3$ageism)
GSS3$racism <- as.factor(GSS3$racism)
GSS3$colltype <- as.factor(GSS3$colltype)
GSS4 <- drop_na(GSS3, DegreeField)
write.csv(GSS4, file = "GSS4.csv")
```


```{r}
library(readr)
GSS5 <- read_csv("~/243project/GSS4.csv")
GSS5$sex <- as.factor(GSS5$sex)
GSS5$race <- as.factor(GSS5$race)
GSS5$maritalstatus <- as.factor(GSS5$maritalstatus)
GSS5$PlaceLived16 <- as.factor(GSS5$PlaceLived16)
GSS5$Region16 <- as.factor(GSS5$Region16)
GSS5$BornHere <- as.factor(GSS5$BornHere)
GSS5$ageism <- as.factor(GSS5$ageism)
GSS5$racism <- as.factor(GSS5$racism)
GSS5$HighestDegree <- as.factor(GSS5$HighestDegree)
GSS5$DegreeField <- as.factor(GSS5$DegreeField)
GSS5$baEarnRate <- as.factor(GSS5$baEarnRate)
GSS5$collStudEnroll <- as.factor(GSS5$collStudEnroll)
GSS5$colltype <- as.factor(GSS5$colltype)
GSS5$jobstatus <- as.factor(GSS5$jobstatus)
GSS5$GovOrPriv <- as.factor(GSS5$GovOrPriv)
GSS5$IndusCode <- as.factor(GSS5$IndusCode)
```

```{r}
GSS6 <- GSS5 %>%
  mutate(STEM = ifelse(DegreeField %in% 
                          c("Biological Sciences", "Engineering and Computer Science",
                            "Mathematics", "Natural Resources & Environment", "Physical Sciences",
                            "Pre-Health & Medicine"), "Yes", "No"))
GSS6$STEM <- as.factor(GSS6$STEM)
summary(GSS6$STEM)
```

### Alternative dataset

```{r}
GSS8 <- subset(GSS4, select = -c(ageism, racism, prestige,IDnum,GSSyear,
                                 IndusCode, collStudEnroll, baEarnRate))
GSS8 <- GSS8 %>%
  mutate(STEM =
           ifelse(
             DegreeField %in% c(
               "Agriculture",
               "Allied health",
               "Biology",
               "Chemistry",
               "Computer science",
               "Electronics",
               "Engineering",
               "Environment science/studies",
               "Food science/nutrition/culinary arts",
               "Forestry",
               "General sciences",
               "Geology",
               "Gerontology",
               "HealthIndustry & techn",
               "Information technology",
               "Mathmatics",
               "Medicine",
               "Pharmacy",
               "Physics",
               "Psychology"
             ), 1, 0
           )
  )
GSS8$STEM <- as.factor(GSS8$STEM)
GSS8$PlaceLived16 <- as.factor(GSS8$PlaceLived16)
GSS8$GovOrPriv <- as.factor(GSS8$GovOrPriv)
GSS8 <- subset(GSS8, select = -DegreeField)
GSS8 <- drop_na(GSS8)
```



### Partitioning the data into test and train sets

```{r}
#Code example found at "https://stackoverflow.com/questions/17200114/how-to-split-data-into-training-testing-sets-using-sample-function"
#setting the proportion of train to test data
n <- floor(0.80 * nrow(GSS8))
#setting a seed for randomization
set.seed(674638)
samp <- sample(seq_len(nrow(GSS8)), size = n)

train <- GSS8[samp,]
test <- GSS8[-samp,]
```

### SVM
```{r}
library(e1071)
SVM <- svm(STEM ~ .-IDnum-GSSyear-X1-DegreeField-collStudEnroll-racism-ageism-baEarnRate-prestige, data = train)
summary(SVM)

```

### Logistic Regression

```{r}
library(caTools)

train2 <-drop_na(train)
glm1 <- glm(STEM ~ .-X1-GSSyear-DegreeField-collStudEnroll-IndusCode-racism-ageism-prestige-baEarnRate, data = train, family = binomial)
summary(glm1)
plot(glm1)


```

